package com.furkan.sso.auth.dao;

import com.furkan.sso.auth.entity.ActiveUser;
import org.springframework.data.repository.CrudRepository;

import javax.transaction.Transactional;
import java.util.List;

/**
 * ActiveUserDao extended from Spring's CrudRepository.
 *
 * All standard crud operations handled by Spring
 *
 * This interface only contains method signitures for spesific requirements like
 * finding rows by token or finding rows by credentials
 *
 * All method implementations will be automatically generated by Spring
 */
@Transactional
public interface ActiveUserDao extends CrudRepository<ActiveUser, Long> {

    /**
     * @param token : auth-token
     * @return Rows containing auth-token parameter's value
     */
    List<ActiveUser> findByToken(String token);

    /**
     * @param credentials : username
     * @return Rows containing credentials parameter's value
     */
    List<ActiveUser> findByCredentials(String credentials);

}
